
[env]
TERM = "xterm-256color"

[window]
opacity = 0.9

[window.dimensions]
columns = 120
lines = 40

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml"
]
